eeprom_i2c_bus=i2c-9
eeprom_chip_type=24c64
eeprom_chip_address=50
vendor=SunFounder
dto_max_current=5000
dto_i2c_enable=-
dto_spi_enable=1
eeprom_pcb_code="P0308V10"
product_name="Pironman 5 Mini"
eeprom_file="o1903v10_pironman_u1.eep"
dt_blob="sunfounder-pironman5mini.dtbo"
dto_ir_enable=-
dto_ir_pin=12
dto_i2s_dac_enable=-
dto_hat_current_supply=0
dto_gpio_poweroff=0
eeprom_custom_data=
